-- https://neon.com/postgresql/postgresql-tutorial/postgresql-char-varchar-text

DROP TABLE IF EXISTS cliente CASCADE;
CREATE TABLE cliente (
    -- id_cliente INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT GENERATED ALWAYS AS IDENTITY,
    email TEXT NOT NULL,
    senha TEXT NOT NULL,
    nome TEXT NOT NULL,
    sobrenome TEXT NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    cep VARCHAR(8) DEFAULT NULL,
    uf VARCHAR(2) DEFAULT NULL,
    cidade TEXT DEFAULT NULL,
    bairro TEXT DEFAULT NULL,
    rua TEXT DEFAULT NULL,
    numero TEXT DEFAULT NULL,
    complemento TEXT DEFAULT NULL,

    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT unique_cpf UNIQUE (cpf)
);


DROP TABLE IF EXISTS produto CASCADE;
CREATE TABLE produto (
    id_produto INT GENERATED ALWAYS AS IDENTITY,
    nome TEXT NOT NULL,
    descricao TEXT DEFAULT NULL,
    preco NUMERIC(10,2) NOT NULL,
    quantidade_estoque INT DEFAULT 0,
    categoria TEXT DEFAULT NULL
);

