-- https://neon.com/postgresql/postgresql-tutorial/postgresql-char-varchar-text

DROP TABLE IF EXISTS cliente CASCADE;
CREATE TABLE cliente (
    -- id_cliente INT GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INT GENERATED ALWAYS AS IDENTITY,
    email TEXT NOT NULL,
    senha TEXT NOT NULL,
    nome TEXT NOT NULL,
    sobrenome TEXT NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    cep VARCHAR(8) DEFAULT NULL,
    uf VARCHAR(2) DEFAULT NULL,
    cidade TEXT DEFAULT NULL,
    bairro TEXT DEFAULT NULL,
    rua TEXT DEFAULT NULL,
    numero TEXT DEFAULT NULL,
    complemento TEXT DEFAULT NULL,

    CONSTRAINT unique_email UNIQUE (email),
    CONSTRAINT unique_cpf UNIQUE (cpf)
);
-- SELECT * FROM cliente LIMIT 10;
CREATE TABLE produto (
    id_produto SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT,
    preco DECIMAL(10,2) NOT NULL,
    quantidade_estoque INT NOT NULL,
    categoria VARCHAR(50)
);
CREATE TABLE carrinho_de_compras (
    id_carrinho SERIAL PRIMARY KEY,
    id_cliente INT NOT NULL,
    data_criacao DATE DEFAULT CURRENT_DATE,
    status VARCHAR(20) DEFAULT 'aberto',
    FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente)
);
CREATE TABLE itens_do_carrinho (
    id_itens_do_carrinho SERIAL PRIMARY KEY,
    id_carrinho INT NOT NULL,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL CHECK (quantidade > 0),
    FOREIGN KEY (id_carrinho) REFERENCES carrinho_de_compras (id_carrinho),
    FOREIGN KEY (id_produto) REFERENCES produto (id_produto)
);

-- TABELA PEDIDO
CREATE TABLE pedido (
    id_pedido SERIAL PRIMARY KEY,
    id_cliente INT NOT NULL,
    id_carrinho INT,
    data_pedido DATE DEFAULT CURRENT_DATE,
    valor_total DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) DEFAULT 'pendente',
    FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
    FOREIGN KEY (id_carrinho) REFERENCES carrinho_de_compras (id_carrinho)
);
CREATE TABLE relatorio (
    id_relatorio SERIAL PRIMARY KEY,
    id_pedido INT NOT NULL,
    data_geracao DATE DEFAULT CURRENT_DATE,
    conteudo TEXT,
    FOREIGN KEY (id_pedido) REFERENCES pedido (id_pedido)
);
