apiVersion: 1

datasources:
# https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/grafana-datasources.yaml
- name: Tempo
  isDefault: false
  editable: true
  type: tempo
  uid: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  version: 1
  apiVersion: 1
  jsonData:
    httpMethod: GET
    tracesToLogsV2:
      datasourceUid: loki
    tracesToMetrics:
      datasourceUid: prometheus
    serviceMap:
      datasourceUid: prometheus
    nodeGraph:
      enabled: true
    streamingEnabled:
      search: true
      metrics: true

- name: Prometheus
  isDefault: true
  editable: true
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  version: 1
  jsonData:
    httpMethod: GET
    exemplarTraceIdDestinations:
      - datasourceUid: tempo
        name: traceID

- name: Loki
  isDefault: false
  editable: true
  type: loki
  uid: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  version: 1
