global:
  scrape_interval: 15s  # Default is every 1 minute.
  # evaluation_interval: 10s  # Evaluate rules. Default is every 1 minute.
  # scrape_timeout  # Default 10s
  # external_labels:
  #     monitor: 'monitoring'


# Alertmanager configuration
# alerting:
  # alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets:
#       - "alertmanager:9093"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# rule_files:
#   - 'alert.rules'


# https://prometheus.io/docs/guides/opentelemetry/
# https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-otlp.yml
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file
otlp:
  # Recommended attributes to be promoted to labels.
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
  # https://prometheus.io/docs/guides/opentelemetry/#including-resource-attributes-at-query-time
  keep_identifying_resource_attributes: true
  # https://prometheus.io/docs/guides/opentelemetry/#utf-8
  # Ingest OTLP data keeping UTF-8 characters in metric/label names.
  # today, this cause a lot of bugs in the Grafana UI
  # translation_strategy: NoTranslation
  # translation_strategy: NoUTF8EscapingWithSuffixes


storage:
  tsdb:
    # OTLP is a push-based protocol, Out of order samples is a common scenario.
    out_of_order_time_window: 30m

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
    # scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']
        # labels:  # The label name is added as a label `label_name=<label_value>` to any timeseries scraped from this config.
        #   app: "prometheus"

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: [cadvisor:8080]

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']
